### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by CrispyCrafter** [DataWookie/2017-06-24-w17-cape-town#1]
Hello Andrew. I attended your software carp talk. Nice to see you started playing with Julia :) 
Is the code for the scraping available ? I wan't to mess around with CSS selectors

**Comment by CrispyCrafter** [comment]
Guess that should do.
https://www.slideshare.net/andrewbcollier/pyconza-2017-web-scraping-unleash-your-internet-viking

**Comment by DataWookie** [comment]
Hey Bernard, I gave all of the material to the conference organisers and they *said* that they would forward it to the people who attended the workshop. They wouldn't give me any email addresses, so I just had to take them at their word. So do you mean that they didn't send you anything? Please confirm before I go and bollocks them. Thanks, Andrew.

**Comment by CrispyCrafter** [comment]
Haha. Hold on, you may want to check with other attendees. From my side, I can confirm nothing was received.

**Comment by DataWookie** [comment]
The irony: I can't check with anybody else since conference organisers would not provide me with any contact details.

**Comment by CrispyCrafter** [comment]
Ok. Maybe check with @James-Burgess. Can confirm presence.

**Comment by DataWookie** [comment]
Hey @James-Burgess, did you get materials from the workshop?

**Comment by James-Burgess** [comment]
Yeah I received the files on October 8th.
I've got them in [this repo](https://github.com/James-Burgess/PyconNotebooks/tree/master/WebScraping)

**Comment by CrispyCrafter** [comment]
Hmm. cannot compute. Thanks @James-Burgess
